[build]
  publish = "build"
  functions = "netlify/functions"

     [[redirects]]
     from = "/api/*"
     to = "/.netlify/functions/backend"
     status = 200
  
 [functions]
  node_bundler = "esbuild"

    [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200